version: "3.8"

services:
    nosql-db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: nosql-db
        volumes:
            - ./db/:/data/db

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: "rabbitmq"
        ports:
            - 5673:5672
            - 15673:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_nodejs

    nginx:
        image: nginx:latest
        ports:
            - "5000:80"
        container_name: nginx
        restart: always
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

    customer:
        build:
            context: ./customer
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
        container_name: customer
        restart: always
        depends_on:
            - nosql-db
            - rabbitmq

    payments:
        build:
            context: ./payments
            dockerfile: Dockerfile
        ports:
            - "5002:5002"
        container_name: payments
        restart: always
        depends_on:
            - nosql-db
            - rabbitmq

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: frontend
        restart: always
        depends_on:
            - nosql-db
            - rabbitmq

networks:
    rabbitmq_nodejs:
        driver: bridge
